public_python/account/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.interview, name='home'),
    url(r'^about/$', views.about, name='about'),
#    url(r'^(?P<id>\d+)/$', views.ad_detail, name='detail'),
#    url(r'^(?P<id>\d+)/edit/$', views.ad_update, name='update'),
#    url(r'^(?P<id>\d+)/delete/$', views.post_delete),
]

public_python/public_python/urls.py
from django.conf.urls import include, url
from django.contrib import admin

admin.autodiscover()

from account import views
from account import urls

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^$', views.home, name='home'),
	url(r'^auction/list/', views.auction_list, name='auction_list'),
	url(r'^auction/create/', views.auction_create, name='auction_create'),
	url(r'^auction/detail/(?P<id>\d+)/$', views.auction_detail, name='auction_detail'),
	url(r'^auction/edit/(?P<id>\d+)/$', views.auction_update, name='auction_update'),
	url(r'^auction/delete/(?P<id>\d+)/$', views.auction_delete, name='auction_delete'),
	#
	url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
	url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', name='logout'),
	url(r'^accounts/loggedin/$', views.loggedin, name='loggedin'),
	#
	url(r'^accounts/register/$', views.register, name='register'),
    url(r'^accounts/register/complete/$', views.registration_complete, name='registration_complete'),
    #
	url(r'^about/$', views.about, name='about'),

]

public_python/account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.forms.formsets import BaseFormSet

from account.choices import *

class ExpandedUser(AbstractUser):
	city = models.CharField(_("city"), max_length=20, blank=True)
	state = models.CharField(_("state"), max_length=20, blank=True)
	zip = models.CharField(_("zip code"), max_length=5, blank=True)


class Question(models.Model):
	question = models.TextField(blank=True)
	answered = models.BooleanField()

class Recipe(models.Model):
	title = models.CharField(max_length=255)
	description = models.TextField()


class Ingredient(models.Model):
	recipe = models.ForeignKey(Recipe)
	description = models.CharField(max_length=255)


class Instruction(models.Model):
	recipe = models.ForeignKey(Recipe)
	number = models.PositiveSmallIntegerField()
	description = models.TextField()

class TodoList(models.Model):
	name = models.CharField(max_length=100)

	def __unicode__(self):
		return self.name


class TodoItem(models.Model):
	name = models.TextField(help_text="e.g. Buy milk, wash dog etc")
	list = models.ForeignKey(TodoList)

	def __unicode__(self):
		return self.name + " (" + str(self.list) + ")"


class AuctionList(models.Model):
	name = models.CharField(max_length=100)
	title = models.CharField(max_length=1000)
	description = models.TextField()
	table = models.TextField()
	grid = models.IntegerField(choices=GRID_CHOICES, default=2)

	def __unicode__(self):
		return self.name


class AuctionAttr(models.Model):
	
	title = models.CharField(max_length=1000)
	description = models.TextField()
	table = models.TextField()
	

class AuctionItem(models.Model):
	photo = models.CharField(max_length=1000)
	list = models.ForeignKey(AuctionList, related_name="photos")

	def __unicode__(self):
		return self.name + " (" + str(self.list) + ")"

public_python/templates/auction/create.html
{% extends "base.html" %}

{% block content %}
<div class="ui page grid">
			<div id="second_menu" class="ui center aligned grid">
				<div class="ui labeled icon menu">
					<a class="item" href="/auction/list/">
						<i class="list layout icon"></i>
						List
					</a>
					<a class="item" href="/">
						<i class="remove circle icon"></i>
						Cancel
					</a>
				</div>
			</div>
</div>

<div class="ui page grid">
	<div class="column">
		<h1 class="ui header">Create new auction</h1>
		<form class="ui form" action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
			<div class="field">
				{{ auction_list_form.name.errors }}
				<label>Name:</label>
				{{ auction_list_form.name }}
			</div>
			<div class="field">
				{{ auction_list_form.title.errors }}
				<label>Auction title:</label>
				{{ auction_list_form.title }}
			</div>
			<div class="field">
				{{ auction_list_form.description.errors }}
				<label>Description:</label>
				{{ auction_list_form.description }}
			</div>
			<div class="field">
				{{ auction_list_form.grid.errors }}
				<label>Grid:</label>
				{{ auction_list_form.grid }}
			</div>
			<div class="field">
				{{ auction_list_form.table.errors }}
				<label>Table:</label>
				{{ auction_list_form.table }}
			</div>

			{{ auction_item_formset.management_form }}
			{% for form in auction_item_formset.forms %}
				{% for field in form %}
				<div class="field photo_field">
					{{ field.errors }}
					<div class="ui fluid icon input">
						{{ field }}
						<a class="ui icon button delete" href="#">
							<i class="ban icon"></i>
						</a>
					</div>
				</div>
				{% endfor %}
			{% endfor %}
			<a id="add" href="#" class="ui basic button right floated text"><i class="icon plus"></i>Add another photo</a>
			<input type="submit" class="ui button" value="Send" />

			<br /><br />
			<div class="ui center aligned grid">
				<button class="ui basic button" id="show_preview">Show preview of this auction</button>
			</div>
		</form>
	</div>
</div>




{{ form.as_p }}


<br /><br /><br /><br /><br /><br /><br /><br /><br />



<div class="ui page grid">
	<div class="column">
<div id="preview_container">
<style>
#menu,h1{text-align: left;width: 800px;margin: 0 auto;}#desc,#gallery,#menu,.gallery,.logo img{margin:0 auto}
#menu,h2{text-transform:uppercase}
.desc-text,.gallery-box{border-left:1px solid #d7928b;border-right:1px solid #d7928b;border-bottom:1px solid #d7928b}
#header{background:url(http://serwer1650393.hostingpremium.pl/top.jpg) center top no-repeat;height:400px}
.logo img{display:block;padding-top:50px}#gallery a,#menu li{display:inline-block}
#menu{font:400 20px/18px Tahoma;letter-spacing:0;padding-top:40px;width:1000px}#gallery img:hover {opacity:0.5}
#menu li{margin-left:20px}#menu li a{color:#fff;text-decoration:none;display:block;
padding:10px 12px;letter-spacing:1px;-webkit-transition:all .3s linear;
-moz-transition:all .3s linear;-o-transition:all .3s linear;transition:all .3s linear;background:#d7928b}
#menu li a:focus,#menu li a:hover{background:#fff;color:#d7928b}#gallery{width:800px}#gallery img{width:200px}
.gallery-box{padding:20px}.gallery{width:615px;}h1{font:34px "Trebuchet MS",sans-serif;color:#383838}#desc{width:800px}
h2{background:url(http://serwer1650393.hostingpremium.pl/bg.jpg);font:20px/20px "Trebuchet MS",sans-serif;padding:10px 15px;
color:#fff;margin-bottom:0}.desc-text{font:12px Arial,sans-serif;padding:10px 20px}
.tg {border-collapse:collapse;border-spacing:0;border-color:#ccc;width:100%;} .tg td{font-family:Arial, sans-serif;
font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;
border-color:#ccc;color:#333;background-color:#fff;} .tg th{font-family:Arial, sans-serif;font-size:14px;
font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;
border-color:#ccc;color:#333;background-color:#f0f0f0;}
</style>
<div id="header">
<div class="logo"><img src="http://serwer1650393.hostingpremium.pl/logo.png" alt="Betique.pl" /></div>
<ul id="menu">
	<li>
		<a href="#">Moje aukcje</a>
	</li><li> 
		<a href="#">Regulamin</a>
	</li><li>
		<a href="#">Komentarze</a>
	</li><li>
		<a href="#">Zadaj pytanie</a>
	</li><li>
		<a href="#">Kontakt</a>
	</li>
</ul>
</div>
<div class="container">
<h1 id="pre_title"></h1>
<div id="desc">
	<h2>Opis produktu</h2>
	<div class="desc-text ">
		<p id="pre_description"></p>
		<p id="pre_table"> </p>
	</div>
</div>
<div id="gallery">
	<h2>Zdjecia produktu</h2>
	<div class="gallery-box">
		<div id="pre_gallery" class="gallery">
		</div>
	</div>
</div>
</div>
</div>

</div>
</div>




{% endblock %}

{% block js %}
<script>
$(document).ready(function () {
	// Code adapted from http://djangosnippets.org/snippets/1389/  
	function updateElementIndex(el, prefix, ndx) {
		var id_regex = new RegExp('(' + prefix + '-\\d+-)');
		var replacement = prefix + '-' + ndx + '-';
		if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex,
		replacement));
		if (el.id) el.id = el.id.replace(id_regex, replacement);
		if (el.name) el.name = el.name.replace(id_regex, replacement);
	}

	function deleteForm(btn, prefix) {
		var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
		if (formCount > 1) {
			// Delete the item/form
			$(btn).parents('.photo_field').remove();
			var forms = $('.photo_field'); // Get all the forms  
			// Update the total number of forms (1 less than before)
			$('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
			var i = 0;
			// Go through the forms and set their indices, names and IDs
			for (formCount = forms.length; i < formCount; i++) {
				$(forms.get(i)).children().children().each(function () {
					if ($(this).attr('type') == 'text') updateElementIndex(this, prefix, i);
				});
			}
		} // End if
		else {
			alert("You have to enter at least one todo item!");
		}
		return false;
	}

	function addForm(btn, prefix) {
		var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
		// You can only submit a maximum of 10 todo items 
		if (formCount < 10) {
			// Clone a form (without event handlers) from the first form
			var row = $(".photo_field:first").clone(false).get(0);
			// Insert it after the last form
			$(row).removeAttr('id').hide().insertAfter(".photo_field:last").slideDown(300);

			// Remove the bits we don't want in the new row/form
			// e.g. error messages
			$(".errorlist", row).remove();
			$(row).children().removeClass("error");

			// Relabel or rename all the relevant bits
			$(row).children().children().each(function () {
				updateElementIndex(this, prefix, formCount);
				$(this).val("");
			});

			// Add an event handler for the delete item/form link 
			$(row).find(".delete").click(function () {
				return deleteForm(this, prefix);
			});
			// Update the total form count
			$("#id_" + prefix + "-TOTAL_FORMS").val(formCount + 1);
		} // End if
		else {
			alert("Sorry, you can only enter a maximum of ten items.");
		}
		return false;
	}

	function showPreview(btn) {
		var name = $("#id_name").val();
		var title = $("#id_title").val();
		var description = $("#id_description").val();
		var table = $("#id_table").val();
		var formCount = parseInt($('#id_form-TOTAL_FORMS').val());
		// alert(name);
		// alert(title);
		// alert(description);
		// alert(table);
		for (i = 0; i < formCount; i++) {
			var photo_url = $("#id_form-" + i + "-photo").val();
			$("#pre_gallery").append('<a href="' + photo_url + '" target="_blank">\n<img src="' + photo_url + '" alt="Zdjęcie nr ' + i + '" />\n</a>\n');
		}
		$("#pre_title").html(title);
		$("#pre_description").html(description);
		$("#pre_table").html(table);
		$("#preview_container").slideDown();
		$('html, body').animate({ scrollTop: 1000 }, 500);
		return false;
	}

	// Register the click event handlers
	$("#add").click(function () {
		return addForm(this, "form");
	});

	$("#delete").click(function () {
		return deleteForm(this, "form");
	});

	$("#show_preview").click(function(){
		return showPreview(this, "preview")
	});
});
</script>
{% endblock %}

public_python/templates/auction/list.html
{% extends "base.html" %}
{% block content %}
<div class="ui page grid">
			<div id="second_menu" class="ui center aligned grid">
				<div class="ui labeled icon menu">
					<a class="item" href="/auction/list/">
						<i class="list layout icon"></i>
						List
					</a>
					<a class="item" href="/auction/create/">
						<i class="plus icon"></i>
						Create
					</a>
				</div>
			</div>
</div>

<div class="ui page grid">
	<div class="column">

<h1 class="ui header">{{ title }}</h1>

<table class="ui celled padded table">
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Auction title</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	{% for obj in object_list %}
		<tr>
			<td>{{ obj.id }}</td>
			<td><a href="/auction/detail/{{ obj.id }}/">{{ obj.name }}</a></td>
			<td>{{ obj.title }}</td>
			<td class="center aligned"><button class="mini ui blue button" onclick="window.location.href='/auction/edit/{{ obj.id }}/'">edit</button></td>
			<td class="center aligned"><button class="mini ui red button" onclick="window.location.href='/auction/delete/{{ obj.id }}/'">delete</button></td>
		</tr>
	{% endfor %}
	</tbody>
</table>


</div>
</div>
{% endblock content %}





public_python/templates/auction/update.html
{% extends "base.html" %}

{% block content %}

<div class="ui page grid">
	<div class="column">
		<h1 class="ui header">Create new auction</h1>
		<form class="ui form" action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
			<div class="field">
				{{ auction_list_form.name.errors }}
				<label>Name:</label>
				{{ auction_list_form.name }}
			</div>
			<div class="field">
				{{ auction_list_form.title.errors }}
				<label>Auction title:</label>
				{{ auction_list_form.title }}
			</div>
			<div class="field">
				{{ auction_list_form.description.errors }}
				<label>Description:</label>
				{{ auction_list_form.description }}
			</div>
			<div class="field">
				{{ auction_list_form.grid.errors }}
				<label>Grid:</label>
				{{ auction_list_form.grid }}
			</div>
			<div class="field">
				{{ auction_list_form.table.errors }}
				<label>Table:</label>
				{{ auction_list_form.table }}
			</div>

			{{ auction_item_formset.management_form }}
			{% for form in auction_item_formset.forms %}
				{% for field in form %}
				<div class="field photo_field">
					{{ field.errors }}
					<div class="ui fluid icon input">
						{{ field }}
						<a class="ui icon button delete" href="#">
							<i class="ban icon"></i>
						</a>
					</div>
				</div>
				{% endfor %}
			{% endfor %}
			<a id="add" href="#" class="ui basic button right floated text"><i class="icon plus"></i>Add another photo</a>
			<input type="submit" class="ui button" value="Send" />

			<br /><br />
			<div class="ui center aligned grid">
				<button class="ui basic button" id="show_preview">Show preview of this auction</button>
			</div>
		</form>
	</div>
</div>




{{ form.as_p }}


<br /><br /><br /><br /><br /><br /><br /><br /><br />



<div class="ui page grid">
	<div class="column">
<div id="preview_container">
<style>
#menu,h1{text-align: left;width: 800px;margin: 0 auto;}#desc,#gallery,#menu,.gallery,.logo img{margin:0 auto}
#menu,h2{text-transform:uppercase}
.desc-text,.gallery-box{border-left:1px solid #d7928b;border-right:1px solid #d7928b;border-bottom:1px solid #d7928b}
#header{background:url(http://serwer1650393.hostingpremium.pl/top.jpg) center top no-repeat;height:400px}
.logo img{display:block;padding-top:50px}#gallery a,#menu li{display:inline-block}
#menu{font:400 20px/18px Tahoma;letter-spacing:0;padding-top:40px;width:1000px}#gallery img:hover {opacity:0.5}
#menu li{margin-left:20px}#menu li a{color:#fff;text-decoration:none;display:block;
padding:10px 12px;letter-spacing:1px;-webkit-transition:all .3s linear;
-moz-transition:all .3s linear;-o-transition:all .3s linear;transition:all .3s linear;background:#d7928b}
#menu li a:focus,#menu li a:hover{background:#fff;color:#d7928b}#gallery{width:800px}#gallery img{width:200px}
.gallery-box{padding:20px}.gallery{width:615px;}h1{font:34px "Trebuchet MS",sans-serif;color:#383838}#desc{width:800px}
h2{background:url(http://serwer1650393.hostingpremium.pl/bg.jpg);font:20px/20px "Trebuchet MS",sans-serif;padding:10px 15px;
color:#fff;margin-bottom:0}.desc-text{font:12px Arial,sans-serif;padding:10px 20px}
.tg {border-collapse:collapse;border-spacing:0;border-color:#ccc;width:100%;} .tg td{font-family:Arial, sans-serif;
font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;
border-color:#ccc;color:#333;background-color:#fff;} .tg th{font-family:Arial, sans-serif;font-size:14px;
font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;
border-color:#ccc;color:#333;background-color:#f0f0f0;}
</style>
<div id="header">
<div class="logo"><img src="http://serwer1650393.hostingpremium.pl/logo.png" alt="Betique.pl" /></div>
<ul id="menu">
	<li>
		<a href="#">Moje aukcje</a>
	</li><li> 
		<a href="#">Regulamin</a>
	</li><li>
		<a href="#">Komentarze</a>
	</li><li>
		<a href="#">Zadaj pytanie</a>
	</li><li>
		<a href="#">Kontakt</a>
	</li>
</ul>
</div>
<div class="container">
<h1 id="pre_title"></h1>
<div id="desc">
	<h2>Opis produktu</h2>
	<div class="desc-text ">
		<p id="pre_description"></p>
		<p id="pre_table"> </p>
	</div>
</div>
<div id="gallery">
	<h2>Zdjecia produktu</h2>
	<div class="gallery-box">
		<div id="pre_gallery" class="gallery">
		</div>
	</div>
</div>
</div>
</div>

</div>
</div>




{% endblock %}

{% block js %}
<script>
$(document).ready(function () {
	// Code adapted from http://djangosnippets.org/snippets/1389/  
	function updateElementIndex(el, prefix, ndx) {
		var id_regex = new RegExp('(' + prefix + '-\\d+-)');
		var replacement = prefix + '-' + ndx + '-';
		if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex,
		replacement));
		if (el.id) el.id = el.id.replace(id_regex, replacement);
		if (el.name) el.name = el.name.replace(id_regex, replacement);
	}

	function deleteForm(btn, prefix) {
		var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
		if (formCount > 1) {
			// Delete the item/form
			$(btn).parents('.photo_field').remove();
			var forms = $('.photo_field'); // Get all the forms  
			// Update the total number of forms (1 less than before)
			$('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
			var i = 0;
			// Go through the forms and set their indices, names and IDs
			for (formCount = forms.length; i < formCount; i++) {
				$(forms.get(i)).children().children().each(function () {
					if ($(this).attr('type') == 'text') updateElementIndex(this, prefix, i);
				});
			}
		} // End if
		else {
			alert("You have to enter at least one todo item!");
		}
		return false;
	}

	function addForm(btn, prefix) {
		var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
		// You can only submit a maximum of 10 todo items 
		if (formCount < 10) {
			// Clone a form (without event handlers) from the first form
			var row = $(".photo_field:first").clone(false).get(0);
			// Insert it after the last form
			$(row).removeAttr('id').hide().insertAfter(".photo_field:last").slideDown(300);

			// Remove the bits we don't want in the new row/form
			// e.g. error messages
			$(".errorlist", row).remove();
			$(row).children().removeClass("error");

			// Relabel or rename all the relevant bits
			$(row).children().children().each(function () {
				updateElementIndex(this, prefix, formCount);
				$(this).val("");
			});

			// Add an event handler for the delete item/form link 
			$(row).find(".delete").click(function () {
				return deleteForm(this, prefix);
			});
			// Update the total form count
			$("#id_" + prefix + "-TOTAL_FORMS").val(formCount + 1);
		} // End if
		else {
			alert("Sorry, you can only enter a maximum of ten items.");
		}
		return false;
	}

	function showPreview(btn) {
		var name = $("#id_name").val();
		var title = $("#id_title").val();
		var description = $("#id_description").val();
		var table = $("#id_table").val();
		var formCount = parseInt($('#id_form-TOTAL_FORMS').val());
		// alert(name);
		// alert(title);
		// alert(description);
		// alert(table);
		for (i = 0; i < formCount; i++) {
			var photo_url = $("#id_form-" + i + "-photo").val();
			$("#pre_gallery").append('<a href="' + photo_url + '" target="_blank">\n<img src="' + photo_url + '" alt="Zdjęcie nr ' + i + '" />\n</a>\n');
		}
		$("#pre_title").html(title);
		$("#pre_description").html(description);
		$("#pre_table").html(table);
		$("#preview_container").slideDown();
		$('html, body').animate({ scrollTop: 1000 }, 500);
		return false;
	}

	// Register the click event handlers
	$("#add").click(function () {
		return addForm(this, "form");
	});

	$("#delete").click(function () {
		return deleteForm(this, "form");
	});

	$("#show_preview").click(function(){
		return showPreview(this, "preview")
	});
});
</script>
{% endblock %}